namespace PsiOrleans.Common.Models;

/// <summary>
/// Represents the result of orchestrating agents for task execution.
/// </summary>
public class OrchestratorResult
{
    /// <summary>
    /// Gets whether the orchestration was successful.
    /// </summary>
    public bool Success { get; init; }

    /// <summary>
    /// Gets the agents that were successfully coordinated.
    /// </summary>
    public IReadOnlyList<AgentId> CoordinatedAgents { get; init; } = new List<AgentId>();

    /// <summary>
    /// Gets the execution plan generated by the orchestrator.
    /// </summary>
    public string ExecutionPlan { get; init; } = string.Empty;

    /// <summary>
    /// Gets the estimated completion time for the coordinated task.
    /// </summary>
    public TimeSpan EstimatedCompletionTime { get; init; }

    /// <summary>
    /// Gets any error messages that occurred during orchestration.
    /// </summary>
    public IReadOnlyList<string> ErrorMessages { get; init; } = new List<string>();

    /// <summary>
    /// Gets the orchestration strategy that was applied.
    /// </summary>
    public string Strategy { get; init; } = string.Empty;

    /// <summary>
    /// Gets additional metadata about the orchestration process.
    /// </summary>
    public IReadOnlyDictionary<string, object> Metadata { get; init; } = new Dictionary<string, object>();
} 